# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FxSWECodNWRVEbyiKb67CifdaZTQ34XY
"""

# Calculadora simples para treinar operações básicas

while True:
    # Entrada dos números
    num1 = input("Digite o primeiro número: ")
    num2 = input("Digite o segundo número: ")

    # Convertendo para float (Erro: não verifica se a entrada é realmente um número)
    num1 = float(num1)
    num2 = float(num2)

    # Exibir opções de operação
    print("\nEscolha a operação:")
    print("1 - Soma")
    print("2 - Subtração")
    print("3 - Multiplicação")
    print("4 - Divisão")
    print("5 - Sair")

    opcao = input("Digite a operação desejada: ")

    # Verificação da operação escolhida
    if opcao == "1":
        print(f"Resultado: {num1} + {num2} = {num1 + num2}")
    elif opcao == "2":
        print(f"Resultado: {num1} - {num2} = {num1 - num2}")
    elif opcao == "3":
        print(f"Resultado: {num1} * {num2} = {num1 * num2}")
    elif opcao == "4":
        if num2 == 0:
            print("Erro! Não é possível dividir por zero.")
        else:
            print(f"Resultado: {num1} / {num2} = {num1 / num2}")
    elif opcao == "5":
        print("Saindo...")
        break
    else:
        print("Opção inválida.")

    print("-" * 30)